[32mINFO[39m:     Started server process [[36m94253[39m]
[32mINFO[39m:     Waiting for application startup.
[32mINFO[39m:     Application startup complete.
[31mERROR[39m:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/fastapi/applications.py", line 290, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vahid/GitHub/lc_qa_chat/app.py", line 45, in answer_question
    documents = ret.get_similar_docs(question=QUESTION)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vahid/GitHub/lc_qa_chat/src/data_connection/retriever.py", line 6, in get_similar_docs
    self.documents = self.vectore_store.similarity_search(question)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 225, in similarity_search
    docs_and_scores = self.similarity_search_with_score(query, k, filter=filter)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 297, in similarity_search_with_score
    query_embedding = self._embedding_function.embed_query(query)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/langchain/embeddings/openai.py", line 536, in embed_query
    embedding = self._embedding_func(text, engine=self.deployment)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/langchain/embeddings/openai.py", line 467, in _embedding_func
    return embed_with_retry(
           ^^^^^^^^^^^^^^^^^
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/langchain/embeddings/openai.py", line 107, in embed_with_retry
    return _embed_with_retry(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/langchain/embeddings/openai.py", line 104, in _embed_with_retry
    response = embeddings.client.create(**kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/openai/api_resources/embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: '$.input' is invalid. Please check the API reference: https://platform.openai.com/docs/api-reference.
[32mINFO[39m:     127.0.0.1:54184 - "[1mGET / HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:54185 - "[1mGET / HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:54207 - "[1mGET / HTTP/1.1[22m" [32m200 OK
0 DOCUMENTS LOADED
[32mINFO[39m:     127.0.0.1:54185 - "[1mGET /answer/?question= HTTP/1.1[22m" [91m500 Internal Server Error
3 DOCUMENTS LOADED
[31mERROR[39m:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/fastapi/applications.py", line 290, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vahid/GitHub/lc_qa_chat/app.py", line 61, in answer_question
    my_table = wandb.Table(columns=response.keys, data=response.values)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/wandb/data_types.py", line 290, in __init__
    self._init_from_list(data, columns, optional, dtype)
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/wandb/data_types.py", line 309, in _init_from_list
    assert type(data) is list, "data argument expects a `list` object"
           ^^^^^^^^^^^^^^^^^^
AssertionError: data argument expects a `list` object
[32mINFO[39m:     127.0.0.1:54193 - "[1mGET /answer/?question=how%20to%20fine-tune%20llama-2 HTTP/1.1[22m" [91m500 Internal Server Error
[32mINFO[39m:     Shutting down
[32mINFO[39m:     Waiting for application shutdown.
[32mINFO[39m:     Application shutdown complete.
[32mINFO[39m:     Finished server process [[36m94253[39m]